name: Keep Jenkins Alive

on:
  schedule:
    - cron: '*/5 * * * *'  # cada 5 minutos

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Jenkins
        run: curl -s https://jenkins2-klot.onrender.com > /dev/null
